### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by fingolfin** [BNasmith/alco#1]
In the README.md you write

> under a GNU General Public License version 3.

I assume you mean "the" not "a"? Otherwise I am confused.

To avoid any ambiguities, I would recommend using the official text recommended (from the end of your `LICENSE.md` file), i.e. like tis (but feel free to remove the liability):

> <one line to give the program's name and a brief idea of what it does.>
> Copyright (C) <year>  <name of author>
>
> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation, either version 3 of the License, or
> (at your option) any later version.
> 
> This program is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> GNU General Public License for more details.
> 
> You should have received a copy of the GNU General Public License
> along with this program.  If not, see <https://www.gnu.org/licenses/>.

Of course that's a slightly different licensing, as it allows GPL 3 *or later*, that's up to you (but the "or later" generally is preferable for us as it is more flexible; actually "GPL 2 or later" is even better from that point of view...).

The licensing terms should also be provided in a machine readable form, by providing a `License` field in `PackageInfo.g` (this will be mandatory in GAP 4.13), with a so-called SPDX identifier for the license. That is:
```
License := "GPL-3.0-or-later",
```
or possibly
```
License := "GPL-3.0",
```

**Comment by BNasmith** [comment]
Yes, I meant "the". Corrected. 

I've copied the `License.md` text into `README.md` file.  

I've also added `License := "GPL-3.0-or-later",` to the `PackageInfo.g` file. 

Thanks for the guidance. If the all works for you, I'll close the issue. If there's more to change I'm happy to do so,
