### ISSUE TITLE
Avoid `x -> foo(x)` pattern

### ISSUE THREAD

**Issue by fingolfin** [BNasmith/alco#12]
Instead of e.g. `Set(gens, x -> Length(x))` just write `Set(gens, Length)`

**Comment by BNasmith** [comment]
I've tried to do this in c483709, for all the cases where `x -> foo(x)` appears. There are still cases where I use `->` because there is no single input function. Please let me know if that's fine or if there are further changes need.

**Comment by BNasmith** [comment]
I've incorporated this advice in the examples as far as possible.
