### ISSUE TITLE
Problematic global names in this package

### ISSUE THREAD

**Issue by fingolfin** [BNasmith/alco#13]
- `OctonionArithmetic` is problematic: this name does not make it clear that it produces an algebra, and in general, it is quite mysterious. At the very least there should be an explanation given.
- `P`, `Alb`, `Oct`, `JTS` are usually considered too short for names of globals in a package. Is this global really needed?
- `P` is a no-go for a deposited package (we have a few single letter functions in GAP itself but mainly because it's too late to change them)

**Comment by BNasmith** [comment]
I've either removed or renamed all of these.
* `OctonionArithmetic` is gone in favour of the ring `OctavianIntegers`. 
* `Alb` and `Oct` are gone but I've we-written the `OctonionAlgebra` and `AlbertAlgebra` functions in a manner that follows the built-in `QuaternionAlgebra` more closely. This addresses the reasons I had the variables `Alb` and `Oct` in the first place without using them. 
* I renamed `P` as `JordanQuadraticOperator` and `JTS` as `JordanTripleSystem`.
