### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by fingolfin** [BNasmith/alco#2]
The `TestFile` specified in `PackageInfo.g` is empty, so this package has zero test coverage, which does not provide much confidence in its workings...

Please set up some actual tests which get run in the test file. At the end of the file, GAP should be quit via `ForceQuitGap(result);` where `result` indicates whether the tests passed (`true`) or failed (`false`). The standard way to set up tests in GAP is via the function `TestDirectory` and `.tst` files, but other ways are possible, as long as the final test result is indicated as above.

**Comment by fingolfin** [comment]
Note that you don't *have* to use `.tst` files but for many things they are maybe most convenient. But you can also keep using your existing `test*.g` files (or even mix them with `.tst` files) with a little bit of thinking and arranging the code suitably. Let me know if you need input on that.

**Comment by BNasmith** [comment]
My main question is how long it would be appropriate for a test to run. Some of the calculations that might be useful can take a minute or longer. If I glean the tests from re-worked documentation examples, hopefully it won't take too long.

**Comment by BNasmith** [comment]
@fingolfin I am using AutoDoc to produce tests and have had some success in the first few chapters. However, in chapter 4, I cannot make the test pass for some reason. Here's what I see in GAP:
```
gap> Test("./tst/alco04.tst");
########> Diff in ./tst/alco04.tst:178
# Input is:
Display(q);
# Expected output:
[ [ [ 10, 16, 1 ], [ 16, 20, 0 ], [ 1, 0, 0 ] ],
  [ [ 12, 15, 0 ], [ 15, 20, 1 ], [ 0, 1, 0 ] ],
  [ [ 27, 0, 0 ], [ 0, 36, 0 ], [ 0, 0, 1 ] ] ]
# But found:
[ [ [ 10, 16, 1 ], [ 16, 20, 0 ], [ 1, 0, 0 ] ],
  [ [ 12, 15, 0 ], [ 15, 20, 1 ], [ 0, 1, 0 ] ],
  [ [ 27, 0, 0 ], [ 0, 36, 0 ], [ 0, 0, 1 ] ] ]
########
alco04.tst
msecs: 67
false
``` 
Here's another example of a failed test:
```
########> Diff in ./tst/alco04.tst:218
# Input is:
DesignAddCardinality(last, DesignSpecialBound(last));
# Expected output:
<Tight 3-design with rank 2, degree 1, cardinality 4, and angle set
[ 0, 1/2 ]>
# But found:
<Tight 3-design with rank 2, degree 1, cardinality 4, and angle set
[ 0, 1/2 ]>
########
```
I note that the width of the test output is 80, and have ensured that my examples all have width 80 when putting them in the xml. Even so, the test is failing when I can discern no difference between the expected output and the actual output. Any ideas?

**Comment by BNasmith** [comment]
I figured it out. I was using,
```
Test("./tst/alco04.tst");
```
But this works instead:
```
Test("./tst/alco04.tst", rec(transformFunction := NormalizedWhitespace));
```

**Comment by BNasmith** [comment]
I am now using the AutoDoc generated tests from the documentation and have the `testall.g` file functioning, as far as I can tell. All tests pass.
