### ISSUE TITLE
Consider using AutoDoc to build the manual

### ISSUE THREAD

**Issue by fingolfin** [BNasmith/alco#5]
The [AutoDoc manual](https://gap-packages.github.io/AutoDoc/doc/chap0_mj.html) describes this in [section 1.3](https://gap-packages.github.io/AutoDoc/doc/chap1_mj.html#X7FA614637B807F4D) and many packages use it for this, see e.g. https://github.com/gap-packages/alnuth/blob/master/makedoc.g

You can also use it to generate the title page from the data in `PackageInfo.g` (this way you only need to update the version and release date in a single place each)

**Comment by fingolfin** [comment]
Also if you use the `extract_examples` section your examples are turned in tests, which on the one hand goes towards resolving issue #2 and on the other hand ensures your tests actually work.

**Comment by BNasmith** [comment]
I'll take a close look at AutoDoc, at first glance it seems quite helpful. Hopefully I can switch to it without much trouble. More to follow.

**Comment by BNasmith** [comment]
I've spent some time on this and seem to have found a working `makedoc.g` file with the code: 
```
LoadPackage("AutoDoc");
LoadPackage("alco");

AutoDoc(rec(
    scaffold := rec( MainPage := false )
));
```
This seems to generate the title page from the `PackageInfo.g` file, which is then included in the `alco.xml` file. 

Regarding extracting examples, I'll need to re-work my examples slightly because some involved checking properties of random elements, which don't display the same way each time. Once I've done this, I'll use AutoDoc to produce the `*.tst` files.

**Comment by BNasmith** [comment]
@fingolfin I've managed to set up the website using your package at https://github.com/gap-system/GitHubPagesForGAP. It should be available as https://bnasmith.github.io/alco. I've also incorporated AutoDoc. If that all looks correct to you, would you be willing to close this issue? I'll work on editing the content of the documentation separately to incorporate your feedback.

**Comment by fingolfin** [comment]
Sure. One final request, though: on https://github.com/BNasmith/alco click the little gear icon right of the text "About" (which is in turn to the right of the green "Code" button). There, activate "Use your GitHub Pages website"

**Comment by BNasmith** [comment]
Done! Thank you
